appname="短视频下载"
appver="1.0.0"
appcode="100"
appsdk="23"
path_pattern="mp4"
packagename="com.jefflemon.video"
theme="Theme_Material"
app_key="151962"
app_channel="官方"
developer="Ryan"
description=""
debugmode=true
user_permission={
  
}
compiles={
  "com.android.support:support-v4:23.4.0",
  "com.android.support:design:23.4.0",
  "com.android.support:appcompat-v7:23.4.0"
}
